npm install;
ng add @angular/material;
npm install --save angular-bootstrap-md;
npm install --save chart.js@2.5.0 @types/chart.js @types/chart.js @fortawesome/fontawesome-free hammerjs;
npm install --save express;
npm install --save-dev nodemon;
npm install --save body-parser;
npm install --save mongoose;
npm install --save multer;
npm install --save mongoose-unique-validator;
npm install --save bcryptjs
npm install --save jsonwebtoken;
npm install --save https;
npm install --save fs;
npm install --save angular-notifier;
npm install --save nodemailer;
npm install --save dinero.js;
npm install --save moment;
npm install --save ng2-charts;
npm install angular-chart.js --save;
